### ISSUE TITLE
Batch comparison tally entry accounts

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1531]
Currently, in batch audits, jurisdiction managers are responsible for batch result data entry. They create audit boards, but the audit boards don't have any way to log in. We should give them the ability to log in in order to distribute the actual data entry work in large batch audits.

**Solution**
Add a new tally entry role for batch audits. JMs can create tally entry accounts that can log in and enter/edit results for any batches.

Tally entry accounts initiate log in with a login link (similar to existing audit board login), but there is just one link for the whole jurisdiction. The JM must enter a code shown on the tally entry account screen in order to confirm the login.

**Implementation details**
- Create a new user type
- JM management flow API endpoints
  - POST turn on (creates log in link)
  - GET login link
  - GET login requests
  - POST confirm login (enter code)
  - DELETE reject login
- Login flow API endpoints
  - POST start login
  - GET login status (and code)

**Implementation plan**
- [x] Remove audit boards from batch audits (1)
- [x] Add tally entry accounts (backend) (2)
- [x] Tally entry accounts - login + tally entry (frontend) (2)
- [x] JM batch audit workflow (frontend) (2)
- [x] Fancier single-digit-at-a-time login code input
- [x] Improve user-facing login errors
- [ ] Refactor and clean up Header components
- [ ] Replace AuthDataContext with useCurrentUser
- [x] Ensure that support tools respects new tally entry accounts (e.g. don't display audit boards)
- [x] Figure out what the jurisdiction progress detail modal should show
- [x] Auto-select the appropriate step based on progress

**Comment by ginvdr** [comment]
This may add complexity but I think jurisdiction manager's in *really* large audits will also want a way to review the data entry from each audit board.  Which somewhat ties into

**Comment by mattroe** [comment]
Potential solution discussed: https://votingworks.slack.com/archives/C01F2CH62TS/p1661189447768099
